apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gowebapp-ingress-root
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: gowebapp.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gowebapp-service
            port:
              number: 80
      - path: /name
        pathType: Prefix
        backend:
          service:
            name: gowebapp-service
            port:
              number: 80
      - path: /bye
        pathType: Prefix
        backend:
          service:
            name: gowebapp-service
            port:
              number: 80
